--3. Script Oracle 19c
--Tabla Principal
CREATE TABLE PRODUCTOS_I (
    ID_PRODUCTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CATEGORIA VARCHAR2(100),
    FECHA_REGISTRO DATE
);

COMMIT;

--Tabla Detalle
CREATE TABLE PRODUCTOS_DETALLE (
    ID_DETALLE NUMBER PRIMARY KEY,
    ID_PRODUCTO NUMBER,
    CODIGO VARCHAR2(50),
    NOMBRE VARCHAR2(100),
    DESCRIPCION VARCHAR2(200),
    PRECIO NUMBER(10,2),
    STOCK NUMBER,
    MARCA VARCHAR2(100),
    ESTADO VARCHAR2(50),

    CONSTRAINT FK_PRODUCTO
    FOREIGN KEY(ID_PRODUCTO)
    REFERENCES PRODUCTOS_I(ID_PRODUCTO)
);

COMMIT;